export const HSN_PRESETS = [
  { code: "996793", label: "Shifting" },
  { code: "998533", label: "Cleaning" },
];

export const INDIAN_STATES = [
  "Maharashtra (27)",
  "Andaman & Nicobar Islands (35)",
  "Andhra Pradesh (37)",
  "Arunachal Pradesh (12)",
  "Assam (18)",
  "Bihar (10)",
  "Chandigarh (04)",
  "Chhattisgarh (22)",
  "Dadra & Nagar Haveli and Daman & Diu (26)",
  "Delhi (07)",
  "Goa (30)",
  "Gujarat (24)",
  "Haryana (06)",
  "Himachal Pradesh (02)",
  "Jammu & Kashmir (01)",
  "Jharkhand (20)",
  "Karnataka (29)",
  "Kerala (32)",
  "Ladakh (38)",
  "Lakshadweep (31)",
  "Madhya Pradesh (23)",
  "Manipur (14)",
  "Meghalaya (17)",
  "Mizoram (15)",
  "Nagaland (13)",
  "Odisha (21)",
  "Puducherry (34)",
  "Punjab (03)",
  "Rajasthan (08)",
  "Sikkim (11)",
  "Tamil Nadu (33)",
  "Telangana (36)",
  "Tripura (16)",
  "Uttar Pradesh (09)",
  "Uttarakhand (05)",
  "West Bengal (19)",
];
